// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	users "alta/air-bnb/features/users"

	mock "github.com/stretchr/testify/mock"
)

// UserData is an autogenerated mock type for the UserDataInterface type
type UserData struct {
	mock.Mock
}

// Delete provides a mock function with given fields: userId
func (_m *UserData) Delete(userId uint) error {
	ret := _m.Called(userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: userData
func (_m *UserData) Insert(userData users.CoreUserRequest) (uint, error) {
	ret := _m.Called(userData)

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(users.CoreUserRequest) (uint, error)); ok {
		return rf(userData)
	}
	if rf, ok := ret.Get(0).(func(users.CoreUserRequest) uint); ok {
		r0 = rf(userData)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(users.CoreUserRequest) error); ok {
		r1 = rf(userData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Select provides a mock function with given fields: userId
func (_m *UserData) Select(userId uint) (users.Core, error) {
	ret := _m.Called(userId)

	var r0 users.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (users.Core, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(uint) users.Core); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(users.Core)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectAll provides a mock function with given fields:
func (_m *UserData) SelectAll() ([]users.CoreGetAllResponse, error) {
	ret := _m.Called()

	var r0 []users.CoreGetAllResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]users.CoreGetAllResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []users.CoreGetAllResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.CoreGetAllResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: userId, userData
func (_m *UserData) Update(userId uint, userData users.CoreUserRequest) error {
	ret := _m.Called(userId, userData)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, users.CoreUserRequest) error); ok {
		r0 = rf(userId, userData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserData interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserData creates a new instance of UserData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserData(t mockConstructorTestingTNewUserData) *UserData {
	mock := &UserData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
